version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rust-backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test_db
    depends_on:
      - mongo

volumes:
  mongo-data:

