name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone rust backend
        run: git clone https://github.com/ImaCodingClown/kanban-board-be.git

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Start backend witn mongo
        run: |
          docker compose up -d
          sleep 10

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
      
      - name: Run tests
        run: npm run test:ci

      - name: TearDown
        run: docker-compose down

